image: gitpod/workspace-dotnet

tasks:
  - init: dotnet restore
    command: dotnet restore /workspace/ZiziBot.NET/src/WinTenBot/WinTenDev.ZiziBot.sln

vscode:
  extensions:
    - muhammad-sammy.csharp
