name: Zizi Bot

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:    
  zizibot-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/ZiziBot.NET/ZiziBot.NET/src/WinTenBot

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.100
      - name: Install dependencies
        run: dotnet restore Zizi.sln

      - name: Linux64 FD Build
        run: dotnet publish Zizi.Bot -r linux-x64 -c Release --self-contained=false
      - name: Upload Linux64 Artifacs
        uses: actions/upload-artifact@v2.2.3
        with:
          name: zizibot-linux64-fd-build.zip
          path: src/WinTenBot/Zizi.Bot/bin/Release/net5.0/linux-x64/publish

      - name: Linux64 FD Single-File Build
        run: dotnet publish Zizi.Bot -r linux-x64 -c Release --self-contained=false /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
      - name: Upload Linux64 Single-File Artifacs
        uses: actions/upload-artifact@v2.2.3
        with:
          name: zizibot-linux64-sf-build.zip
          path: src/WinTenBot/Zizi.Bot/bin/Release/net5.0/linux-x64/publish

      - name: Win64 FD Build
        run: dotnet publish Zizi.Bot -r win-x64 -c Release --self-contained=false
      - name: Upload Win64 FD Artifacs
        uses: actions/upload-artifact@v2.2.3
        with:
          name: zizibot-win64-fd-build.zip
          path: src/WinTenBot/Zizi.Bot/bin/Release/net5.0/win-x64/publish

      - name: Win64 FD Single-File Build
        run: dotnet publish Zizi.Bot -r win-x64 -c Release --self-contained=false /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
      - name: Upload Win64 SF Artifacs
        uses: actions/upload-artifact@v2.2.3
        with:
          name: zizibot-win64-sf-build.zip
          path: src/WinTenBot/Zizi.Bot/bin/Release/net5.0/win-x64/publish
